# Generated by Django 5.2.9 on 2025-12-02 22:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Badge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Nombre')),
                ('description', models.TextField(verbose_name='Descripcion')),
                ('icon_name', models.CharField(help_text='Nombre del icono CSS o archivo', max_length=50)),
                ('criteria', models.CharField(help_text="Clave interna para la IA (ej: 'rock_lover')", max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.TextField(blank=True, max_length=500, verbose_name='Biografia')),
                ('avatar', models.ImageField(default='avatars/default.jpg', upload_to='avatars/', verbose_name='Avatar')),
                ('badges', models.ManyToManyField(blank=True, related_name='owners', to='users.badge')),
                ('follows', models.ManyToManyField(blank=True, related_name='followed_by', to='users.profile')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
