# Generated by Django 5.2.9 on 2025-12-03 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='is_private',
            field=models.BooleanField(default=False, verbose_name='Privado'),
        ),
    ]
