# Generated by Django 5.2.9 on 2025-12-03 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0004_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='bpm',
            field=models.IntegerField(blank=True, null=True, verbose_name='BPM (Velocidad)'),
        ),
        migrations.AddField(
            model_name='song',
            name='energy',
            field=models.FloatField(blank=True, null=True, verbose_name='Nivel de Energía'),
        ),
    ]
