# Generated by Django 5.2.9 on 2025-12-04 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0005_song_bpm_song_energy'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='full_audio_file',
            field=models.FileField(blank=True, null=True, upload_to='tracks/full_hq/'),
        ),
    ]
